language: python
python:
  - "3.8"

sudo: false
cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio
  - platformio update

script:
  - platformio run -e basic
  - platformio run -e enhanced

notifications:
  email:
    on_success: change
    on_failure: change
